### ISSUE TITLE
Progress toward Quality Level 1

### ISSUE THREAD

**Issue by Blast545** [ros2/rosidl_defaults#6]
This issue tracks the progression of packages in `rosidl_defaults` that have been deemed necessary for Quality Level 1 and a 1.0 version. It follows the outline described in [REP 2004](https://github.com/ros-infrastructure/rep/blob/c2ba03bac23b8f313e47820833fad000dbbe058b/rep-2004.rst). 

The packages slated for Quality Level 1 for ROS 2 Foxy are:
- rosidl_default_runtime

Excluded for Quality Level 1 at this time:
- rosidl_default_generators

# Progress rosidl_default_runtime:
* [x] Version Policy
    - Follows ROS Core Quality Declaration
* [x] Version >= 1.0.0
* [x] Change Control Process
    - Recommended guidelines for ROS Core packages in the [ROS 2 Developer Guide](https://index.ros.org/doc/ros2/Contributing/Developer-Guide/#package-requirements)
* [x] API and ABI stability within a ROS distribution
* [x] Vulnerability Disclosure Policy

Documentation
* [x] Per-feature documentation.
* [x] Per-item documentation in public API.  
   - Does not have features / API
* [x] Declared set of licenses
* [x] Copyright statement in each source file
    - No source files, not copyrighted
* [x] Quality Declaration document

Testing:
* [x] System tests, which cover "features", API Testing, Coverage, Performance testing
   - Not required
* [x] Linters and Static Analysis:
  - * [x] Must have a code style and enforce it.
  - * [x] Must use static analysis tools where applicable: 
  -- See [Linters ROS 2 Developer Guide](https://index.ros.org/doc/ros2/Contributing/Developer-Guide/#linters)

Dependencies:
* [x] Runtime "ROS" dependencies are level 1
    - rosidl_runtime
    - rosidl_typesupport_c
    - rosidl_typesupport_cpp
* [x] non-ROS dependencies are equivalent level 1
    - None

Platform Support
* [x] Supports all tier 1 platforms as described in [REP-2000](https://www.ros.org/reps/rep-2000.html#support-tiers)

**Comment by chapulina** [comment]
Level 1 achieved! https://github.com/ros2/rosidl_defaults/pull/15/
